  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
.
me->ANCESTOR = ANCESTOR .
me->NODE = NODE .
me->VALID_FROM = VALID_FROM .
me->VALID_TO = VALID_TO .
me->TABLE_NAME = TABLE_NAME .
clear me->textid.
if textid is initial.
  IF_T100_MESSAGE~T100KEY = IF_T100_MESSAGE=>DEFAULT_TEXTID.
else.
  IF_T100_MESSAGE~T100KEY = TEXTID.
endif.
  endmethod.