CLASS ltc_ngc_bil_cls_class DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_cls_class.
ENDCLASS.

CLASS ltc_ngc_bil_cls_classcharc DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_cls_classcharc.
ENDCLASS.

CLASS ltc_ngc_bil_cls_classdesc DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_cls_classdesc.
ENDCLASS.

CLASS ltc_ngc_bil_cls_classkeyword DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_cls_classkeyword.
ENDCLASS.

CLASS ltc_ngc_bil_cls_classtext DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_cls_classtext.
ENDCLASS.

CLASS ltc_ngc_bil_cls_transactional DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_cls_transactional.
ENDCLASS.