interface IF_EX_NGC_CLF_NODE_LEAF
  public .


  interfaces IF_BADI_INTERFACE .

  methods GET_NODE_LEAF
    importing
      !IV_CLASSTYPE type KLASSENART
      !IS_CLASSIFICATION_KEY type NGCS_CLASSIFICATION_KEY
      !IT_CLASSIFICATION_REF_DATA type NGCT_CLASSIFICATION_REF_DATA
    changing
      !CV_PROCESSING_NODE type BOOLE_D
      !CS_PARENT_CLASSIFICATION_KEY type NGCS_CLASSIFICATION_KEY
      !CT_CHILD_CLASSIFICATION_KEY type NGCT_CLASSIFICATION_KEY
      !CT_MESSAGE type SYMSG_TAB optional .
endinterface.