*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LNGC_CORE_CLSV01 .
FUNCTION $$UNIT$$ NGC_CORE_CLS_HIER_GENERATE

    TABLES
       !LT_CLINT TYPE !TT_CLINT_RANGE .