*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LNGC_CORE_CLSV02 .

FUNCTION $$UNIT$$ NGC_CORE_CLS_HIER_UPD_TASK

    IMPORTING
       VALUE(IT_CLHIER_IDX_INSERT) TYPE !NGCT_CLHIER_IDX
       VALUE(IT_CLHIER_IDX_UPDATE) TYPE !NGCT_CLHIER_IDX
       VALUE(IT_CLHIER_IDX_DELETE) TYPE !NGCT_CLHIER_IDX
    EXCEPTIONS
       !UPDATE_FAILED
       !MODIFY_FAILED
       !DELETE_FAILED .