*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FORM NGC_CORE_CLS_HIER_GENERATE USING %_KEY.
* Parameter declaration
DATA %_P0000000001 TYPE
TT_CLINT_RANGE
  WITH HEADER LINE.
DATA: %_STATE.
* Assign default values
* Get mode for update task
  CALL 'GET_SWITCH_UTASK'
   ID 'MODE'  FIELD 'S'
   ID 'STATE' FIELD %_STATE.
  IF %_STATE EQ 'N'.
* Import from memory
  IMPORT
    LT_CLINT TO %_P0000000001
  FROM MEMORY ID %_KEY.
  ELSE.
* Import from logfile
  IMPORT
    LT_CLINT TO %_P0000000001
  FROM LOGFILE ID %_KEY.
  ENDIF.
* Call update task
  CALL FUNCTION 'NGC_CORE_CLS_HIER_GENERATE'
     TABLES
       LT_CLINT = %_P0000000001
  .
ENDFORM.