*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LNGC_CORE_CLSU02.
                    "NGC_CORE_CLS_HIER_UPD_TASK
INCLUDE LNGC_CORE_CLSU01.
                    "NGC_CORE_CLS_HIER_GENERATE