  METHOD get_charc_basic_2018.

    rt_charc_basic = VALUE #(
      ( charcinternalid              = '0000000003'
        timeintervalnumber           = '0000'
        characteristic               = 'CHARACTERISTIC_03'
        charcidentificationcode      = ''
        charcstatus                  = ''
        charcdatatype                = 'CHAR'
        charclength                  = '30'
        charcdecimals                = ''
        charctemplate                = ''
        valueiscasesensitive         = ''
        charcconversionroutine       = ''
        charcgroup                   = ''
        entryisrequired              = ''
        multiplevaluesareallowed     = ''
        charcvalueunit               = ''
        currency                     = ''
        charcexponentformat          = ''
        charcexponentvalue           = ''
        valueintervalisallowed       = ''
        additionalvalueisallowed     = ''
        negativevalueisallowed       = ''
        validitystartdate            = '20180101'
        validityenddate              = '20181231'
        changenumber                 = ''
        isdeleted                    = ''
        documentinforecorddoctype    = ''
        documentinforecorddocnumber  = ''
        documentinforecorddocversion = ''
        documentinforecorddocpart    = ''
        charcmaintauthgrp            = ''
        charcisreadonly              = ''
        charcishidden                = ''
        charcreferencetable          = ''
        charcreferencetablefield     = ''
        charcchecktable              = ''
        charccheckfunctionmodule     = ''
        charcentryisnotformatctrld   = ''
        charctemplateisdisplayed     = ''
        charcselectedset             = ''
        plant                        = ''
        charccatalogtype             = ''
        createdbyuser                = ''
        creationdate                 = ''
        lastchangedbyuser            = ''
        lastchangedate               = '20181105'
        charclastchangeddatetime     = '' )
    ).

  ENDMETHOD.