  method GET_CHARC_BASIC_OVR_2017.

    rt_charc_basic = VALUE #(
      ( charcinternalid              = cv_charc_02_id
        timeintervalnumber           = '0000'
        characteristic               = 'CHARACTERISTIC_OVERWRITE'
        charcidentificationcode      = ''
        charcstatus                  = ''
        charcdatatype                = 'CHAR'
        charclength                  = '30'
        charcdecimals                = ''
        charctemplate                = ''
        valueiscasesensitive         = ''
        charcconversionroutine       = ''
        charcgroup                   = ''
        entryisrequired              = ''
        multiplevaluesareallowed     = ''
        charcvalueunit               = ''
        currency                     = ''
        charcexponentformat          = ''
        charcexponentvalue           = ''
        valueintervalisallowed       = ''
        additionalvalueisallowed     = ''
        negativevalueisallowed       = ''
        validitystartdate            = '20170101'
        validityenddate              = '20171231'
        changenumber                 = ''
        isdeleted                    = ''
        documentinforecorddoctype    = ''
        documentinforecorddocnumber  = ''
        documentinforecorddocversion = ''
        documentinforecorddocpart    = ''
        charcmaintauthgrp            = ''
        charcisreadonly              = ''
        charcishidden                = ''
        charcreferencetable          = ''
        charcreferencetablefield     = ''
        charcchecktable              = ''
        charccheckfunctionmodule     = ''
        charcentryisnotformatctrld   = ''
        charctemplateisdisplayed     = ''
        charcselectedset             = ''
        plant                        = ''
        charccatalogtype             = ''
        createdbyuser                = ''
        creationdate                 = ''
        lastchangedbyuser            = ''
        lastchangedate               = '20171105'
        charclastchangeddatetime     = '' )
    ).

  endmethod.