protected section.

  data MO_CHR_BAPI_UTIL type ref to IF_NGC_RAP_CHR_BAPI_UTIL .
  data MS_CHR_MULTIPLE type A_CLFNCHARACTERISTICFORKEYDATE .
  data MS_CHR_DESC_EN type A_CLFNCHARCDESCFORKEYDATE .
  data MS_CHR_DESC_DE type A_CLFNCHARCDESCFORKEYDATE .
  data MS_CHR_REF type A_CLFNCHARCREFFORKEYDATE .
  data MS_CHR_RSTRCN type A_CLFNCHARCRSTRCNFORKEYDATE .
  data MS_CHR_VAL_CHAR type A_CLFNCHARCVALUEFORKEYDATE .
  data MS_CHR_VAL_DESC_EN type A_CLFNCHARCVALUEDESCFORKEYDATE .

  methods CREATE_CHARACTERISTIC
    importing
      !IS_CHARC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARC optional
      !IT_CHARCDESC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCDESC optional
      !IT_CHARCREF type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCREF optional
      !IT_CHARCRSTRCN type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCRSTRCN optional
      !IT_CHARCVALUEDESC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCVALUEDESC optional
      !IT_CHARCVALUE type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCVALUE optional
    returning
      value(RV_CHARCINTERNALID) type A_CLFNCHARACTERISTICFORKEYDATE-CHARCINTERNALID .
  methods CREATE_CHARACTERISTICDESC
    importing
      !IS_CHARCDESC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARCDESC optional
      !IV_NAVIGATION type BOOLE_D default ABAP_FALSE
    returning
      value(RV_CHARCINTERNALID) type A_CLFNCHARACTERISTICFORKEYDATE-CHARCINTERNALID .
  methods CREATE_CHARACTERISTICREF
    importing
      !IS_CHARCRSTRCN type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARCRSTRCN optional
    returning
      value(RV_CHARCINTERNALID) type A_CLFNCHARACTERISTICFORKEYDATE-CHARCINTERNALID .
  methods CREATE_CHARACTERISTICRSTRCN
    importing
      !IS_CHARCREF type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARCREF optional
    returning
      value(RV_CHARCINTERNALID) type A_CLFNCHARACTERISTICFORKEYDATE-CHARCINTERNALID .
  methods DELETE_CHARACTERISTIC
    importing
      !IV_CHARCINTERNALID type A_CLFNCHARACTERISTICFORKEYDATE-CHARCINTERNALID .
  methods DELETE_CHARACTERISTICDESC
    importing
      !IV_CHARCINTERNALID type ATINN
      !IV_LANGUAGE type SPRAS .
  methods DELETE_CHARACTERISTICREF
    importing
      !IV_CHARCINTERNALID type ATINN
      !IV_REFERENCETABLE type ATTAB
      !IV_REFERENCEFIELD type ATFEL .
  methods DELETE_CHARACTERISTICRSTRCN
    importing
      !IV_CHARCINTERNALID type ATINN
      !IV_CLASSTYPE type KLASSENART .
  methods DELETE_CHARACTERISTICVAL
    importing
      !IV_CHARCINTERNALID type ATINN
      !IV_CHARCVALUEPOSITIONNUMBER type ATZHL .
  methods UPDATE_CHARACTERISTIC
    importing
      !IS_CHARC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARC .
  methods UPDATE_CHARACTERISTICDESC
    importing
      !IS_CHARC_DESC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARCDESC .
  methods UPDATE_CHARACTERISTICVAL
    importing
      !IS_CHARC_VAL type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARCVALue .
  methods GET_ATTRIBUTE_VALUE_FROM_XML
    importing
      !IV_XML type STRING
      !IV_ATTRIBUTE_NAME type STRING
    returning
      value(RV_VALUE) type STRING .
  methods DELETE_CHR_WITH_BAPI
    importing
      !IV_CHARACTERISTIC type ATNAM .
  methods VALIDATE_RESULT
    importing
      !IS_CHARC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-S_CHARC
      !IT_CHARC_DESC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCDESC optional
      !IT_CHARC_REF type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCREF optional
      !IT_CHARC_RSTRCN type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCRSTRCN optional
      !IT_CHARC_VAL type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCVALUE optional
      !IT_CHARC_VAL_DESC type CL_NGC_BIL_CHR=>LTY_CLFN_CHARC_CDS-T_CHARCVALUEDESC optional .

  methods GET_SERVICE_NAME
    redefinition .