private section.

  data MT_CHARACTERISTIC_ORG_AREA type NGCT_CLASSIFICATION_ORG_AREA .
  data MO_API_FACTORY type ref to CL_NGC_API_FACTORY .
  data MS_CLASS_HEADER type NGCS_CLASS .
  data MT_CHARACTERISTIC type NGCT_CLASS_CHARACTERISTIC .
  data MT_CHARACTERISTIC_OBJECT type NGCT_CHARACTERISTIC_OBJECT .
  data MO_CLS_PERSISTENCY type ref to IF_NGC_CORE_CLS_PERSISTENCY .
  data MV_CHARACTERISTICS_POPULATED type BOOLE_D value ABAP_FALSE ##NO_TEXT.