interface IF_NGC_CLF_VALIDATION_DP
  public .


  methods SET_UPDATED_DATA
    importing
      !IT_CLASSIFICATION_DATA_UPD type NGCT_CLASSIFICATION_DATA_UPD optional
      !IT_ASSIGNED_CLASS_UPD type NGCT_CLASS_OBJECT_UPD optional
      !IT_ASSIGNED_VALUES type NGCT_VALUATION_DATA_UPD optional .
  methods GET_VALIDATION_CLASS_TYPES
    returning
      value(RT_CLASSTYPE) type NGCT_CLASS_TYPES .
  methods CLEAR_VALIDATION_CLASS_TYPES .
  methods UPDATE_ASSIGNED_VALUES
    importing
      !IT_VALUES type NGCT_VALUATION_CHARCVALUE_CHG .
  methods GET_CLASSTYPE_NODE_OR_LEAF
    importing
      !IV_CLASSTYPE type KLASSENART
    exporting
      !EV_IS_NODE type BOOLE_D
      !ES_PARENT_CLASSIFICATION_KEY type NGCS_CLASSIFICATION_KEY
      !ET_CHILD_CLASSIFICATION_KEY type NGCT_CLASSIFICATION_KEY .
endinterface.