*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FORM SAMPLE_PROCESS_01010002 %_RFC.
* Parameter declaration
DATA RFCDEST                        TYPE
RFCDEST
.
DATA SPRSL                          TYPE
LANGU
.
DATA ARBGB                          TYPE
ARBGB
.
DATA MSGNR                          TYPE
MSGNR
.
DATA TEXT LIKE T100-TEXT .
DATA GRU1 LIKE CMFP-GRU1 .
DATA GRU2 LIKE CMFP-GRU2 .
DATA VEBE LIKE CMFP-VEBE .
DATA VBFIX LIKE CMFP-VBFIX .
DATA TCMF1_MSG                      TYPE
CHAR1
.
* Assign default values
  SPRSL = SY-LANGU .
* Call remote function
  CALL FUNCTION 'SAMPLE_PROCESS_01010002' %_RFC
     EXPORTING
       RFCDEST = RFCDEST
       SPRSL = SPRSL
       ARBGB = ARBGB
       MSGNR = MSGNR
     IMPORTING
       TEXT = TEXT
       GRU1 = GRU1
       GRU2 = GRU2
       VEBE = VEBE
       VBFIX = VBFIX
       TCMF1_MSG = TCMF1_MSG
  .
ENDFORM.