*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCR_PAIRSU01.
                    "TABLEFRAME_ZCR_PAIRS
INCLUDE LZCR_PAIRSU02.
                    "TABLEPROC_ZCR_PAIRS