interface IF_NGC_CLASSIFICATION
  public .


  methods GET_CLASSIFICATION_KEY
    returning
      value(RS_CLASSIFICATION_KEY) type NGCS_CLASSIFICATION_KEY .
  methods GET_ASSIGNED_CLASSES
    exporting
      !ET_CLASSIFICATION_DATA type NGCT_CLASSIFICATION_DATA
      !ET_ASSIGNED_CLASS type NGCT_CLASS_OBJECT .
  methods ASSIGN_CLASSES
    importing
      !IT_CLASS type NGCT_CLASS_OBJECT
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods ASSIGN_CLASSES_BY_EXT_KEY
    importing
      !IT_CLASS_EXT_KEY type NGCT_CLASS_KEY_EXT
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods ASSIGN_CLASSES_BY_INT_KEY
    importing
      !IT_CLASS_INT_KEY type NGCT_CLASS_KEY
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods REMOVE_CLASSES
    importing
      !IT_CLASS type NGCT_CLASS_OBJECT
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods REMOVE_CLASSES_BY_EXT_KEY
    importing
      !IT_CLASS_EXT_KEY type NGCT_CLASS_KEY_EXT
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods REMOVE_CLASSES_BY_INT_KEY
    importing
      !IT_CLASS_INT_KEY type NGCT_CLASS_KEY
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods GET_ASSIGNED_VALUES
    importing
      !IV_CLASSTYPE type KLASSENART optional
    exporting
      !ET_VALUATION_DATA type NGCT_VALUATION_DATA
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods CHANGE_VALUES
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCVALUE_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_CHANGE_VALUE type NGCT_VALUATION_CHARCVALUE_CHG .
  methods GET_DOMAIN_VALUES
    importing
      !IV_CLASSTYPE type KLASSENART
      !IV_CHARCINTERNALID type ATINN
    exporting
      !ET_DOMAIN_VALUE type NGCT_CHARACTERISTIC_VALUE
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods GET_UPDATED_DATA
    exporting
      !ET_CLASSIFICATION_DATA_UPD type NGCT_CLASSIFICATION_DATA_UPD
      !ET_ASSIGNED_CLASS_UPD type NGCT_CLASS_OBJECT_UPD
      !ET_VALUATION_DATA_UPD type NGCT_VALUATION_DATA_UPD
      !ET_VALUATION_DATA_PREV type NGCT_VALUATION_DATA_UPD .
  methods VALIDATE
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods MODIFY_CLASSIFICATION_DATA
    importing
      !IT_CLASSIFICATION_DATA_MOD type NGCT_CLASSIFICATION_DATA_MOD
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods GET_CHARACTERISTICS
    importing
      !IV_CLASSTYPE type KLASSENART optional
      !IV_CHARCINTERNALID type ATINN optional
    exporting
      !ET_CHARACTERISTIC type NGCT_CLF_CHARACTERISTIC_OBJECT
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods SET_REFERENCE_DATA
    importing
      !IV_CHARCREFERENCETABLE type ATTAB
      !IR_DATA type ref to DATA .
  methods GET_REFERENCE_DATA
    importing
      !IV_CHARCREFERENCETABLE type ATTAB
    returning
      value(RR_DATA) type ref to DATA .
  methods CHANGE_STATUS
    importing
      !IV_CLASSINTERNALID type CLINT
      !IV_STATUS type CLSTATUS
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods GET_CLASSTYPES
    returning
      value(RT_CLASSTYPE) type NGCT_CLASSTYPE .
  methods REFRESH_CLF_STATUS
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods UPDATE_TEMPORARY_KEY
    importing
      !IV_CLFNOBJECTID type CUOBN
    raising
      CX_NGC_API .
  methods SET_CHARACTER_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_CHAR_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CHAR_CHG .
  methods DELETE_CHARACTER_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_CHAR_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CHAR_CHG .
  methods CHANGE_CHARACTER_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_CHAR_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CHAR_CHG .
  methods SET_CURRENCY_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_CURR_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CURR_CHG .
  methods DELETE_CURRENCY_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_CURR_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CURR_CHG .
  methods CHANGE_CURRENCY_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_CURR_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CURR_CHG .
  methods SET_NUMERIC_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_NUM_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_NUM_CHG .
  methods DELETE_NUMERIC_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_NUM_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_NUM_CHG .
  methods CHANGE_NUMERIC_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_NUM_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_NUM_CHG .
  methods SET_DATE_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_DATE_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_DATE_CHG .
  methods DELETE_DATE_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_DATE_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_DATE_CHG .
  methods CHANGE_DATE_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_DATE_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_DATE_CHG .
  methods SET_TIME_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_TIME_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_TIME_CHG .
  methods DELETE_TIME_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_TIME_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_TIME_CHG .
  methods CHANGE_TIME_VALUE
    importing
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCV_TIME_CHG
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !ET_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_TIME_CHG .
  methods GET_INTERNAL_OBJECT_NUMBER
    returning
      value(RT_OBJ_INT_ID) type NGCT_CLF_OBJ_INT_ID .
  methods LOCK_ALL
    importing
      !IV_CLASSTYPE type KLASSENART optional
    exporting
      !EO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
endinterface.