*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LBTOPU07.   "OUTBOUND_CALL_01010002_P
INCLUDE LBTOPU09.   "OUTBOUND_CALL_01010003_P
INCLUDE LBTOPU01.   "OUTBOUND_CALL_00503121_P
INCLUDE LBTOPU02.   "OUTBOUND_CALL_00503122_P
INCLUDE LBTOPU03.   "OUTBOUND_CALL_00503140_P