CLASS tc_ngc_core_chr_pers_checktab DEFINITION
  PUBLIC
  INHERITING FROM tc_ngc_core_chr_pers_base
  ABSTRACT
  CREATE PUBLIC
  FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS .

  PUBLIC SECTION.