CLASS ltc_ngc_bil_clf_object DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_clf_object.
ENDCLASS.

CLASS ltc_ngc_bil_clf_objectclass DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_clf_objectclass.
ENDCLASS.

CLASS ltc_ngc_bil_clf_objectcharc DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_clf_objectcharc.
ENDCLASS.

CLASS ltc_ngc_bil_clf_objectcharcval DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_clf_objectcharcval.
ENDCLASS.

CLASS ltc_ngc_bil_clf_transactional DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS
  FINAL
  INHERITING FROM tc_ngc_bil_clf_transactional.
ENDCLASS.