private section.

  constants GC_FLOAT_EPS type ATFLV value '0.00000000000001' ##NO_TEXT.
  class-data GO_INSTANCE type ref to CL_NGC_CORE_CLS_UTIL_INTERSECT .

  methods CALC_INTERSECT_CHAR_TYPE
    importing
      !IT_COLLECTED_CHAR_VALUES type NGCT_CORE_CLASS_CHARC_INTER
    exporting
      !ES_COLLECTED_CHAR_VALUE type NGCS_CORE_CLASS_CHARC_INTER .
  methods CALC_INTERSECT_NOT_CHAR_TYPE
    importing
      !IT_COLLECTED_CHAR_VALUES type NGCT_CORE_CLASS_CHARC_INTER
    exporting
      !ES_COLLECTED_CHAR_VALUE type NGCS_CORE_CLASS_CHARC_INTER .
  methods CALC_FLOAT_INTERVAL_INTERSECT
    importing
      !IV_NEGATIVEVALUEISALLOWED type ATVOR
      !IS_FLOAT_1 type IF_NGC_CORE_CLS_UTIL_INTERSECT~TS_FLOAT_VALUE
      !IS_FLOAT_2 type IF_NGC_CORE_CLS_UTIL_INTERSECT~TS_FLOAT_VALUE
    returning
      value(RS_FLOAT_INTERSECTION) type IF_NGC_CORE_CLS_UTIL_INTERSECT~TS_FLOAT_VALUE .
  methods CHECK_FLOAT_VALUE_INTERSECT
    importing
      !IS_FLOAT_1 type IF_NGC_CORE_CLS_UTIL_INTERSECT~TS_FLOAT_VALUE
      !IS_FLOAT_2 type IF_NGC_CORE_CLS_UTIL_INTERSECT~TS_FLOAT_VALUE
    returning
      value(RV_HAS_INTERSECTION) type BOOLE_D .
  methods SIMPLIFY_VALUE
    importing
      !IS_CHAR_VALUE type NGCS_CORE_CHARC_VALUE_DATA
    returning
      value(RS_CHAR_VALUE) type NGCS_CORE_CHARC_VALUE_DATA .
  methods GET_ITEMS_WITH_INTERSECTION
    importing
      !IT_COLLECTED_CHAR_VALUES type NGCT_CORE_CLASS_CHARC_INTER
    returning
      value(RT_INTERSECT_CHAR_VALUES) type NGCT_CORE_CLASS_CHARC_INTER .