*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZABAPGIT_PARALLELU01.
                    "Z_ABAPGIT_SERIALIZE_PARALLEL