PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_OBJEK.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !LANGUAGE MODULE %_LANGUAGE .

FIELD !LOG2FILE MODULE %_LOG2FILE .

FIELD !TESTMODE MODULE %_TESTMODE .

CHAIN.
  FIELD  OBJEK-LOW.
  FIELD  OBJEK-HIGH.
  MODULE %_OBJEK.
ENDCHAIN.

CHAIN.
  FIELD LANGUAGE .
  FIELD LOG2FILE .
  FIELD TESTMODE .
  FIELD  OBJEK-LOW.
  FIELD  OBJEK-HIGH.
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.