class CL_API_CLFN_CHARACTERI_MPC definition
  public
  inheriting from /IWBEP/CL_MGW_PUSH_ABS_MODEL
  create public .

public section.

  interfaces IF_SADL_GW_MODEL_EXPOSURE_DATA .

  types:
   TS_A_CLFNCHARACTERISTICFORKEYD type A_CLFNCHARACTERISTICFORKEYDATE .
  types:
   TT_A_CLFNCHARACTERISTICFORKEYD type standard table of TS_A_CLFNCHARACTERISTICFORKEYD .
  types:
   TS_A_CLFNCHARCDESCFORKEYDATETY type A_CLFNCHARCDESCFORKEYDATE .
  types:
   TT_A_CLFNCHARCDESCFORKEYDATETY type standard table of TS_A_CLFNCHARCDESCFORKEYDATETY .
  types:
   TS_A_CLFNCHARCREFFORKEYDATETYP type A_CLFNCHARCREFFORKEYDATE .
  types:
   TT_A_CLFNCHARCREFFORKEYDATETYP type standard table of TS_A_CLFNCHARCREFFORKEYDATETYP .
  types:
   TS_A_CLFNCHARCRSTRCNFORKEYDATE type A_CLFNCHARCRSTRCNFORKEYDATE .
  types:
   TT_A_CLFNCHARCRSTRCNFORKEYDATE type standard table of TS_A_CLFNCHARCRSTRCNFORKEYDATE .
  types:
   TS_A_CLFNCHARCVALUEDESCFORKEYD type A_CLFNCHARCVALUEDESCFORKEYDATE .
  types:
   TT_A_CLFNCHARCVALUEDESCFORKEYD type standard table of TS_A_CLFNCHARCVALUEDESCFORKEYD .
  types:
   TS_A_CLFNCHARCVALUEFORKEYDATET type A_CLFNCHARCVALUEFORKEYDATE .
  types:
   TT_A_CLFNCHARCVALUEFORKEYDATET type standard table of TS_A_CLFNCHARCVALUEFORKEYDATET .

  constants GC_A_CLFNCHARACTERISTICFORKEYD type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_ClfnCharacteristicForKeyDateType' ##NO_TEXT.
  constants GC_A_CLFNCHARCDESCFORKEYDATETY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_ClfnCharcDescForKeyDateType' ##NO_TEXT.
  constants GC_A_CLFNCHARCREFFORKEYDATETYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_ClfnCharcRefForKeyDateType' ##NO_TEXT.
  constants GC_A_CLFNCHARCRSTRCNFORKEYDATE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_ClfnCharcRstrcnForKeyDateType' ##NO_TEXT.
  constants GC_A_CLFNCHARCVALUEDESCFORKEYD type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_ClfnCharcValueDescForKeyDateType' ##NO_TEXT.
  constants GC_A_CLFNCHARCVALUEFORKEYDATET type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_ClfnCharcValueForKeyDateType' ##NO_TEXT.

  methods DEFINE
    redefinition .
  methods GET_LAST_MODIFIED
    redefinition .