*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_01000902

    TABLES
       !PCM_PCMHB_TAB_T STRUCTURE !PCMHB
       !PCM_PCMPB_TAB_T STRUCTURE !PCMPB .