*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_00004050

    TABLES
       !I_IBIN_BTE_APO_1_TAB STRUCTURE !IBINBTE_APO_1 .