*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_01000011

    TABLES
       !XMSEG STRUCTURE !MSEG .