*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_01000901
         TABLES
               !ET_ALLOCATION_TAB STRUCTURE !RMCLKSSK OPTIONAL
               !ET_VALUE_TAB STRUCTURE !RMCLAUSP OPTIONAL
               !ET_DELOB_TAB STRUCTURE !RMCLDOB OPTIONAL .