*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_01000792

    IMPORTING
       VALUE(PI_BUFFER_REFRESH) TYPE !XFELD DEFAULT ' '
    TABLES
       !IT_POSGUID STRUCTURE !MEPO_POSGUID OPTIONAL .