*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_01000770

    TABLES
       !PTI_XEKBE STRUCTURE !EKBE OPTIONAL
       !PTI_YEKBE STRUCTURE !EKBE OPTIONAL .