*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_01000010
         IMPORTING
               VALUE(BUDAT) LIKE !MKPF-BUDAT DEFAULT SY-DATLO
               VALUE(USNAM) LIKE !MKPF-USNAM DEFAULT SY-UNAME
         TABLES
               !XMARC STRUCTURE !SMARC
               !XMARD STRUCTURE !SMARD
               !XMCH1 STRUCTURE !SMCH1
               !XMCHA STRUCTURE !SMCHA
               !XMCHB STRUCTURE !SMCHB
               !XMKOL STRUCTURE !SMKOL
               !XMSKA STRUCTURE !SMSKA
               !XMSKU STRUCTURE !SMSKU
               !XMSLB STRUCTURE !SMSLB
               !XMSPR STRUCTURE !SMSPR
               !XMSSA STRUCTURE !SMSSA
               !XMSSL STRUCTURE !SMSSL
               !XMSSQ STRUCTURE !SMSSQ .