*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ SAMPLE_INTERFACE_01000760

    TABLES
       !PTI_EKBE STRUCTURE !EKBE OPTIONAL
       !PTI_SBETS STRUCTURE !MESBETS OPTIONAL .