interface IF_NGC_BIL_CLS
  public .


  methods CREATE_CLASS
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_REPORTED .
  methods DELETE_CLASS
    importing
      !IT_DELETE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_REPORTED .
  methods UPDATE_CLASS
    importing
      !IT_UPDATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_REPORTED .
  methods CREATE_CLASS_DESC
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_REPORTED .
  methods CREATE_CLASS_DESC_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_REPORTED .
  methods UPDATE_CLASS_DESC
    importing
      !IT_UPDATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_REPORTED .
  methods CREATE_CLASS_KEYWORD
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_REPORTED .
  methods CREATE_CLASS_KEYWORD_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_REPORTED .
  methods DELETE_CLASS_KEYWORD
    importing
      !IT_DELETE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_REPORTED .
  methods UPDATE_CLASS_KEYWORD
    importing
      !IT_UPDATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_REPORTED .
  methods CREATE_CLASS_TEXT
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_REPORTED .
  methods CREATE_CLASS_TEXT_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_REPORTED .
  methods DELETE_CLASS_TEXT
    importing
      !IT_DELETE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_REPORTED .
  methods UPDATE_CLASS_TEXT
    importing
      !IT_UPDATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_REPORTED .
  methods CREATE_CLASS_CHARC
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_REPORTED .
  methods CREATE_CLASS_CHARC_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_REPORTED .
  methods DELETE_CLASS_CHARC
    importing
      !IT_DELETE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_REPORTED .
  methods UPDATE_CLASS_CHARC
    importing
      !IT_UPDATE type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_REPORTED .
  methods READ_CLASS
    importing
      !IT_CLASS type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_READ_IN
    exporting
      !ET_CLASS type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTP-T_FAILED .
  methods READ_CLASS_DESC
    importing
      !IT_CLASS_DESC type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_READ_IN
    exporting
      !ET_CLASS_DESC type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSDESCTP-T_FAILED .
  methods READ_CLASS_KEYWORD
    importing
      !IT_CLASS_KEYWORD type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_READ_IN
    exporting
      !ET_CLASS_KEYWORD type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSKEYWORDTP-T_FAILED .
  methods READ_CLASS_TEXT
    importing
      !IT_CLASS_TEXT type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_READ_IN
    exporting
      !ET_CLASS_TEXT type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSTEXTTP-T_FAILED .
  methods READ_CLASS_CHARC
    importing
      !IT_CLASS_CHARC type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_READ_IN
    exporting
      !ET_CLASS_CHARC type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CLS_C=>LTY_CLFNCLASSCHARCTP-T_FAILED .
endinterface.