private section.

  methods GET_MAPPING_CHARACTERISTIC
    exporting
      !ET_FIELD_MAPPING type IF_VDM_PLMB_API_MAPPER=>GTY_TS_FIELD_MAPPING .
  methods GET_MAPPING_CHARCDESC
    exporting
      !ET_FIELD_MAPPING type IF_VDM_PLMB_API_MAPPER=>GTY_TS_FIELD_MAPPING .
  methods GET_MAPPING_CHARCRSTR
    exporting
      !ET_FIELD_MAPPING type IF_VDM_PLMB_API_MAPPER=>GTY_TS_FIELD_MAPPING .
  methods GET_MAPPING_CHARCREF
    exporting
      !ET_FIELD_MAPPING type IF_VDM_PLMB_API_MAPPER=>GTY_TS_FIELD_MAPPING .
  methods GET_MAPPING_CHARCVAL
    exporting
      !ET_FIELD_MAPPING type IF_VDM_PLMB_API_MAPPER=>GTY_TS_FIELD_MAPPING .
  methods GET_MAPPING_CHARCVAL_DESC
    exporting
      !ET_FIELD_MAPPING type IF_VDM_PLMB_API_MAPPER=>GTY_TS_FIELD_MAPPING .