interface IF_NGC_CORE_CLS_PERSISTENCY
  public .


  methods CLEANUP .
  methods READ_BY_EXTERNAL_KEY
    importing
      !IT_KEYS type NGCT_CORE_CLASS_KEY_EXT
      !IV_LOCK type BOOLE_D default ABAP_FALSE
    exporting
      !ET_CLASSES type NGCT_CORE_CLASS
      !ET_CLASS_CHARACTERISTICS type NGCT_CORE_CLASS_CHARACTERISTIC
      !ET_CLASS_CHARACTERISTIC_VALUES type NGCT_CORE_CLASS_CHARC_VALUE
      !ET_CHARACTERISTIC_REFERENCE type NGCT_CORE_CHARC_REF
      !ET_MESSAGE type NGCT_CORE_CLASS_MSG .
  methods READ_BY_INTERNAL_KEY
    importing
      !IT_KEYS type NGCT_CORE_CLASS_KEY
      !IV_LOCK type BOOLE_D default ABAP_FALSE
    exporting
      !ET_CLASSES type NGCT_CORE_CLASS
      !ET_CLASS_CHARACTERISTICS type NGCT_CORE_CLASS_CHARACTERISTIC
      !ET_CLASS_CHARACTERISTIC_VALUES type NGCT_CORE_CLASS_CHARC_VALUE
      !ET_CHARACTERISTIC_REFERENCE type NGCT_CORE_CHARC_REF
      !ET_MESSAGE type NGCT_CORE_CLASS_MSG .
  methods READ_CLASS_STATUS
    importing
      !IV_CLASSTYPE type KLASSENART
      !IV_CLASSSTATUS type KLSTATUS
    returning
      value(RS_CLASS_STATUS) type NGCS_CORE_CLASS_STATUS .
  methods READ_CLASS_STATUSES
    importing
      !IV_CLASSTYPE type KLASSENART
    returning
      value(RT_CLASS_STATUS) type NGCT_CORE_CLASS_STATUS .
endinterface.