private section.

  class-data GO_INSTANCE type ref to CL_NGC_CLF_UTIL_VALUATION_EXT .

  methods GET_DECIMAL_BOUNDARIES
    importing
      !IV_CHARCFROMNUMERICVALUE type ATFLV
      !IV_CHARCTONUMERICVALUE type ATFLB
      !IV_CHARCVALUEDEPENDENCY type ATCOD
      !IV_CHARCLENGTH type ANZST optional
      !IV_CHARCDECIMALS type ANZDZ
    exporting
      !EV_CHARCTODECIMALVALUE type AUSPEXT_DEC_TO
      !EV_CHARCFROMDECIMALVALUE type AUSPEXT_DEC_FROM .
  methods CONVERT_FLTP_TO_DEC
    importing
      !IV_FLTP_VALUE type FLTP_VALUE
      !IV_DECIMALS type ANZDZ
    returning
      value(RV_DEC_VALUE) type AUSPEXT_DEC_FROM
    exceptions
      CONVERSION_ERROR .
  methods GET_CURRENCY_BOUNDARIES
    importing
      !IV_CHARCFROMNUMERICVALUE type ATFLV
      !IV_CHARCTONUMERICVALUE type ATFLB
      !IV_CHARCVALUEDEPENDENCY type ATCOD
      !IV_CHARCLENGTH type ANZST optional
      !IV_CURRENCY type WAERS_CURC
    exporting
      !EV_CHARCTOAMOUNT type AUSPEXT_CURR_TO
      !EV_CHARCFROMAMOUNT type AUSPEXT_CURR_FROM
    exceptions
      CONVERSION_ERROR .
  methods CONVERT_FLTP_TO_CURR
    importing
      !IV_FLTP_VALUE type FLTP_VALUE
      !IV_CURRENCY type WAERS optional
    returning
      value(RV_CURR_VALUE) type AUSPEXT_CURR_FROM
    exceptions
      CONVERSION_ERROR .
  methods GET_DATE_BOUNDARIES
    importing
      !IV_CHARCFROMNUMERICVALUE type ATFLV
      !IV_CHARCTONUMERICVALUE type ATFLB
      !IV_CHARCVALUEDEPENDENCY type ATCOD
    exporting
      !EV_CHARCTODATE type AUSPEXT_DATE_TO
      !EV_CHARCFROMDATE type AUSPEXT_DATE_FROM .
  methods GET_TIME_BOUNDARIES
    importing
      !IV_CHARCFROMNUMERICVALUE type ATFLV
      !IV_CHARCTONUMERICVALUE type ATFLB
      !IV_CHARCVALUEDEPENDENCY type ATCOD
    exporting
      !EV_CHARCTOTIME type AUSPEXT_TIME_TO
      !EV_CHARCFROMTIME type AUSPEXT_TIME_FROM .