protected section.

  data MO_CUT type ref to CL_NGC_BIL_CLF .
  data MO_NGC_CHARACTERISTIC type ref to IF_NGC_CHARACTERISTIC .
  data MT_NGC_CHARACTERISTIC type NGCT_CLF_CHARACTERISTIC_OBJECT .

  methods SETUP_API_RESULT
    importing
      !IV_MSGTY type SYST_MSGTY optional
      !IT_MESSAGE type NGCT_CLASSIFICATION_MSG optional
    returning
      value(RO_NGC_CLF_API_RESULT) type ref to CL_NGC_CLF_API_RESULT .
  methods SETUP_API_READ
    importing
      !IS_CLASSIFICATION_KEY type NGCS_CLASSIFICATION_KEY optional
      !IT_CLASSIFICATON_OBJECT type NGCT_CLASSIFICATION_OBJECT optional
      !IO_NGC_CLF_API_RESULT type ref to CL_NGC_CLF_API_RESULT .
  methods SETUP_API_READ_MULTI
    importing
      !IT_CLASSIFICATION_KEY type NGCT_CLASSIFICATION_KEY optional
      !IO_NGC_CLF_API_RESULT type ref to CL_NGC_CLF_API_RESULT .
  methods SETUP_API_VALIDATE
    importing
      !IO_NGC_CLF_API_RESULT type ref to CL_NGC_CLF_API_RESULT .
  methods SETUP_API_UPDATE
    importing
      !IO_NGC_CLF_API_RESULT type ref to CL_NGC_CLF_API_RESULT .
  methods SETUP_CLASS_ASSIGN
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_NGC_CLF_API_RESULT type ref to CL_NGC_CLF_API_RESULT .
  methods SETUP_CLASS_REMOVE
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_NGC_CLF_API_RESULT type ref to CL_NGC_CLF_API_RESULT .
  methods VERIFY_API_SETUP .
  methods VERIFY_CLASSIFICATION_SETUP .
  methods VERIFY_CHARACTERISTIC_SETUP .
  methods SETUP_GET_CHARACTERISTICS
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IT_CHARACTERISTIC type NGCT_CLF_CHARACTERISTIC_OBJECT
      !IO_NGC_CLF_API_RESULT type ref to CL_NGC_CLF_API_RESULT .
  methods SETUP_GET_ASSIGNED_CLASSES
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type INT4
      !IT_CLASSIFICATION_DATA type NGCT_CLASSIFICATION_DATA
      !IT_ASSIGNED_CLASS type NGCT_CLASS_OBJECT .
  methods SETUP_GET_ASSIGNED_VALUES
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type INT4
      !IT_VALUATION_DATA type NGCT_VALUATION_DATA
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods SETUP_GET_INTERNAL_OBJECT_NUM
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type INT4
      !IT_OBJ_INT_ID type NGCT_CLF_OBJ_INT_ID .
  methods SETUP_CHANGE_VALUES
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCVALUE_CHG .
  methods SETUP_CHANGE_VALUE
    importing
      !IV_CHARCDATATYPE type ATFOR
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IT_TEST_DATA type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-CREATE-T_INPUT optional
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods SETUP_SET_VALUE
    importing
      !IV_CHARCDATATYPE type ATFOR
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IT_TEST_DATA type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-CREATE-T_INPUT optional
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT .
  methods SETUP_DELETE_CURR_VALUE
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !IT_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CURR_CHG .
  methods SETUP_DELETE_DATE_VALUE
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !IT_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_DATE_CHG .
  methods SETUP_DELETE_CHAR_VALUE
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !IT_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_CHAR_CHG .
  methods SETUP_DELETE_NUM_VALUE
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !IT_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_NUM_CHG .
  methods SETUP_DELETE_TIME_VALUE
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IO_CLF_API_RESULT type ref to IF_NGC_CLF_API_RESULT
      !IT_SUCCESS_VALUE type NGCT_VALUATION_CHARCV_TIME_CHG .
  methods SETUP_CHARC_GET_HEADER
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I
      !IV_CHARCDATATYPE type ATFOR .
  methods SETUP_CHARC_GET_HEADER_DELETE
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I .
  methods GET_TESTDATA_FOR_CREATE
    importing
      !IV_CHARCDATATYPE type ATFOR
    returning
      value(RT_OBJECTCHARCVAL_CREATE) type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-CREATE-T_INPUT .
  methods GET_TESTDATA_FOR_UPDATE
    importing
      !IV_CHARCDATATYPE type ATFOR
    returning
      value(RT_OBJECTCHARCVAL_UPDATE) type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-UPDATE-T_INPUT .
  methods GET_VALUATION_DATA
    importing
      !IV_CHARCDATATYPE type ATFOR
    returning
      value(RT_VALUATION_DATA) type NGCT_VALUATION_DATA .
  methods SETUP_SET_REFERENCE_DATA
    importing
      !IV_NUMBER_OF_EXPECTED_CALLING type I .
  methods GET_RESPONSES
    exporting
      !ES_MAPPED type IF_NGC_BIL_CLF=>TS_MAPPED
      !ES_REPORTED type IF_NGC_BIL_CLF=>TS_REPORTED
      !ES_FAILED type IF_NGC_BIL_CLF=>TS_FAILED
      !ES_MAPPED_LATE type IF_NGC_BIL_CLF=>TS_MAPPED_LATE
      !ES_REPORTED_LATE type IF_NGC_BIL_CLF=>TS_REPORTED_LATE
      !ES_FAILED_LATE type IF_NGC_BIL_CLF=>TS_FAILED_LATE .