interface IF_NGC_BIL_CHR
  public .


  methods CREATE_CHARC
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_REPORTED .
  methods DELETE_CHARC
    importing
      !IT_DELETE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_REPORTED .
  methods UPDATE_CHARC
    importing
      !IT_UPDATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_REPORTED .
  methods CREATE_CHARC_DESC
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_REPORTED .
  methods CREATE_CHARC_DESC_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_REPORTED .
  methods DELETE_CHARC_DESC
    importing
      !IT_DELETE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_REPORTED .
  methods UPDATE_CHARC_DESC
    importing
      !IT_UPDATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_REPORTED .
  methods CREATE_CHARC_RSTR
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_REPORTED .
  methods CREATE_CHARC_RSTR_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_REPORTED .
  methods DELETE_CHARC_RSTR
    importing
      !IT_DELETE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_REPORTED .
  methods CREATE_CHARC_REF
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_REPORTED .
  methods CREATE_CHARC_REF_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_REPORTED .
  methods DELETE_CHARC_REF
    importing
      !IT_DELETE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_REPORTED .
  methods CREATE_CHARC_VAL
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_REPORTED .
  methods CREATE_CHARC_VAL_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_REPORTED .
  methods DELETE_CHARC_VAL
    importing
      !IT_DELETE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_REPORTED .
  methods UPDATE_CHARC_VAL
    importing
      !IT_UPDATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_REPORTED .
  methods CREATE_CHARC_VAL_DESC
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_CREATE
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_REPORTED .
  methods CREATE_CHARC_VAL_DESC_DIRECT
    importing
      !IT_CREATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_CREATE_DIRECT
    exporting
      !ET_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_MAPPED
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_REPORTED .
  methods DELETE_CHARC_VAL_DESC
    importing
      !IT_DELETE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_DELETE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_REPORTED .
  methods UPDATE_CHARC_VAL_DESC
    importing
      !IT_UPDATE type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_UPDATE
    exporting
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_FAILED
      !ET_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_REPORTED .
  methods READ_CHARC
    importing
      !IT_CHARC type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_READ_IN
    exporting
      !ET_CHARC type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_FAILED .
  methods READ_CHARC_DESC
    importing
      !IT_CHARC_DESC type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_READ_IN
    exporting
      !ET_CHARC_DESC type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_FAILED .
  methods READ_CHARC_RSTR
    importing
      !IT_CHARC_RSTR type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_READ_IN
    exporting
      !ET_CHARC_RSTR type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_FAILED .
  methods READ_CHARC_REF
    importing
      !IT_CHARC_REF type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_READ_IN
    exporting
      !ET_CHARC_REF type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_FAILED .
  methods READ_CHARC_VAL
    importing
      !IT_CHARC_VAL type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_READ_IN
    exporting
      !ET_CHARC_VAL type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_FAILED .
  methods READ_CHARC_VAL_DESC
    importing
      !IT_CHARC_VAL_DESC type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_READ_IN
    exporting
      !ET_CHARC_VAL_DESC type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_READ_OUT
      !ET_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_FAILED .
endinterface.