*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ OUTBOUND_CALL_01000106_E

         TABLES
               !IT_AFPO_BT STRUCTURE !AFPOB
!IT_RESB_BT STRUCTURE !RESBB .