*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ OUTBOUND_CALL_00004050_E

    TABLES
       !I_IBIN_BTE_APO_1_TAB STRUCTURE !IBINBTE_APO_1 .