*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FORM OUTBOUND_CALL_01000792_E USING %_KEY.
* Parameter declaration
DATA %_P0000000001 TYPE
XFELD
.
DATA BEGIN OF %_P0000000002 OCCURS 10.
INCLUDE STRUCTURE
MEPO_POSGUID
.
DATA END OF %_P0000000002.
DATA: %_STATE.
* Assign default values
  %_P0000000001 = ' ' .
* Get mode for update task
  CALL 'GET_SWITCH_UTASK'
   ID 'MODE'  FIELD 'S'
   ID 'STATE' FIELD %_STATE.
  IF %_STATE EQ 'N'.
* Import from memory
  IMPORT
    PI_BUFFER_REFRESH TO %_P0000000001
    IT_POSGUID TO %_P0000000002
  FROM MEMORY ID %_KEY.
  ELSE.
* Import from logfile
  IMPORT
    PI_BUFFER_REFRESH TO %_P0000000001
    IT_POSGUID TO %_P0000000002
  FROM LOGFILE ID %_KEY.
  ENDIF.
* Call update task
  CALL FUNCTION 'OUTBOUND_CALL_01000792_E'
     EXPORTING
       PI_BUFFER_REFRESH = %_P0000000001
     TABLES
       IT_POSGUID = %_P0000000002
  .
ENDFORM.