*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ OUTBOUND_CALL_01000780_E

    IMPORTING
       REFERENCE(IM_BSTYP) LIKE !EKKO-BSTYP
    EXPORTING
       REFERENCE(EX_KALSM) LIKE !EKKO-KALSM .