*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ OUTBOUND_CALL_01000902_E

    TABLES
       !PCM_PCMHB_TAB_T STRUCTURE !PCMHB
       !PCM_PCMPB_TAB_T STRUCTURE !PCMPB .