*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FORM OUTBOUND_CALL_01000791_E USING %_KEY.
* Parameter declaration
DATA %_P0000000001 TYPE
CS_GUIDC
.
DATA: %_STATE.
* Assign default values
* Get mode for update task
  CALL 'GET_SWITCH_UTASK'
   ID 'MODE'  FIELD 'S'
   ID 'STATE' FIELD %_STATE.
  IF %_STATE EQ 'N'.
* Import from memory
  IMPORT
    I_TRGUID TO %_P0000000001
  FROM MEMORY ID %_KEY.
  ELSE.
* Import from logfile
  IMPORT
    I_TRGUID TO %_P0000000001
  FROM LOGFILE ID %_KEY.
  ENDIF.
* Call update task
  CALL FUNCTION 'OUTBOUND_CALL_01000791_E'
     EXPORTING
       I_TRGUID = %_P0000000001
  .
ENDFORM.