*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LBTOCV09 .

FUNCTION $$UNIT$$ OUTBOUND_CALL_01000792_E

    IMPORTING
       VALUE(PI_BUFFER_REFRESH) TYPE !XFELD DEFAULT ' '
    TABLES
       !IT_POSGUID STRUCTURE !MEPO_POSGUID OPTIONAL .