*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LBTOCV19 .

FUNCTION $$UNIT$$ OUTBOUND_CALL_01000901_E
         TABLES
               !ET_ALLOCATION_TAB STRUCTURE !RMCLKSSK
               !ET_VALUE_TAB STRUCTURE !RMCLAUSP
               !ET_DELOB_TAB STRUCTURE !RMCLDOB .