*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ OUTBOUND_CALL_01000770_E

    TABLES
       !PTI_XEKBE STRUCTURE !EKBE OPTIONAL
       !PTI_YEKBE STRUCTURE !EKBE OPTIONAL .