*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LBTOCV07 .

FUNCTION $$UNIT$$ OUTBOUND_CALL_01000791_E

    IMPORTING
       VALUE(I_TRGUID) TYPE !CS_GUIDC OPTIONAL .