*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ OUTBOUND_CALL_01000760_E

    TABLES
       !PTI_EKBE STRUCTURE !EKBE OPTIONAL
       !PTI_SBETS STRUCTURE !MESBETS OPTIONAL .