*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LBTOCV13 .

FUNCTION $$UNIT$$ OUTBOUND_CALL_01000601_E

    TABLES
       !XPBABX STRUCTURE !PBABX .