*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FORM OUTBOUND_CALL_01000601_E USING %_KEY.
* Parameter declaration
DATA BEGIN OF %_P0000000001 OCCURS 10.
INCLUDE STRUCTURE
PBABX
.
DATA END OF %_P0000000001.
DATA: %_STATE.
* Assign default values
* Get mode for update task
  CALL 'GET_SWITCH_UTASK'
   ID 'MODE'  FIELD 'S'
   ID 'STATE' FIELD %_STATE.
  IF %_STATE EQ 'N'.
* Import from memory
  IMPORT
    XPBABX TO %_P0000000001
  FROM MEMORY ID %_KEY.
  ELSE.
* Import from logfile
  IMPORT
    XPBABX TO %_P0000000001
  FROM LOGFILE ID %_KEY.
  ENDIF.
* Call update task
  CALL FUNCTION 'OUTBOUND_CALL_01000601_E'
     TABLES
       XPBABX = %_P0000000001
  .
ENDFORM.