*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LBTOCV10 .

FUNCTION $$UNIT$$ OUTBOUND_CALL_01000011_E

    TABLES
       !XMSEG STRUCTURE !MSEG
       !/SPE/PLANTRIGGER_TIMESTAMP STRUCTURE
       !/SPE/PLANTRIGGER_AFS_TIMESTAMP OPTIONAL .