class CL_NGC_UTIL_MESSAGE definition
  public
  final
  create public .

public section.

  class-methods CONVERT_MSG_CHR_TO_CLF
    importing
      !IT_CHARACTERISTIC_MSG type NGCT_CHARACTERISTIC_MSG
    exporting
      !ET_CLASSIFICATION_MSG type NGCT_CLASSIFICATION_MSG .
  class-methods CONVERT_MSG_CLS_TO_CLF
    importing
      !IT_CLASS_MSG type NGCT_CLASS_MSG
    exporting
      !ET_CLASSIFICATION_MSG type NGCT_CLASSIFICATION_MSG .
  class-methods CONVERT_MSG_CORECHR_TO_CLF
    importing
      !IS_CLASSIFICATION_KEY type NGCS_CLASSIFICATION_KEY optional
      !IS_CLF_CHARACTERISTIC_KEY type NGCS_CLF_CHARACTERISTIC_KEY optional
      !IV_CHARCVALUEPOSITIONNUMBER type WZAEHL optional
      !IT_CORE_CHARC_MSG type NGCT_CORE_CHARC_MSG
    exporting
      !ET_CLASSIFICATION_MSG type NGCT_CLASSIFICATION_MSG .
  class-methods CONVERT_MSG_CORECHR_TO_CORECLF
    importing
      !IS_CLASSIFICATION_KEY type NGCS_CLASSIFICATION_KEY optional
      !IS_CLF_CHARACTERISTIC_KEY type NGCS_CLF_CHARACTERISTIC_KEY optional
      !IV_CHARCVALUEPOSITIONNUMBER type WZAEHL optional
      !IT_CORE_CHARC_MSG type NGCT_CORE_CHARC_MSG
    exporting
      !ET_CORE_CLASSIFICATION_MSG type NGCT_CORE_CLASSIFICATION_MSG .
  class-methods CONVERT_MSG_CORECLS_TO_CORECLF
    importing
      !IS_CLASSIFICATION_KEY type NGCS_CORE_CLASSIFICATION_KEY optional
      !IT_CORE_CLASS_MSG type NGCT_CORE_CLASS_MSG
    exporting
      !ET_CORE_CLASSIFICATION_MSG type NGCT_CORE_CLASSIFICATION_MSG .