*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZCR_GAMESU01.
                    "TABLEFRAME_ZCR_GAMES
INCLUDE LZCR_GAMESU02.
                    "TABLEPROC_ZCR_GAMES