*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ NGC_INT_DRF_BTE_00004002

    TABLES
       !I_ALLOCATION_TAB STRUCTURE !RMCLKSSK OPTIONAL
       !I_VALUE_TAB STRUCTURE !RMCLAUSP OPTIONAL
       !I_DELOB_TAB STRUCTURE !RMCLDOB OPTIONAL .