*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LNGC_INT_DRF_BTEU01.
                    "NGC_INT_DRF_BTE_00004000
INCLUDE LNGC_INT_DRF_BTEU02.
                    "NGC_INT_DRF_BTE_00004001
INCLUDE LNGC_INT_DRF_BTEU03.
                    "NGC_INT_DRF_BTE_00004002