*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LNGC_CORE_CLFV01 .

FUNCTION $$UNIT$$ NGC_CORE_CLF_DB_UPDATE

    IMPORTING
       VALUE(IT_KSSK_UPDATE) TYPE !NGCT_CORE_CLF_KSSK_UPD
       VALUE(IT_INOB_UPDATE) TYPE !NGCT_CORE_CLF_INOB_UPD
       VALUE(IT_AUSP_UPDATE) TYPE !NGCT_CORE_CLF_AUSP_UPD
    EXCEPTIONS
       !INSERT_FAILED
       !UPDATE_FAILED
       !DELETE_FAILED .