*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FORM NGC_CORE_CLF_DB_UPDATE USING %_KEY.
* Parameter declaration
DATA %_P0000000001 TYPE
NGCT_CORE_CLF_KSSK_UPD
.
DATA %_P0000000002 TYPE
NGCT_CORE_CLF_INOB_UPD
.
DATA %_P0000000003 TYPE
NGCT_CORE_CLF_AUSP_UPD
.
DATA: %_STATE.
* Assign default values
* Get mode for update task
  CALL 'GET_SWITCH_UTASK'
   ID 'MODE'  FIELD 'S'
   ID 'STATE' FIELD %_STATE.
  IF %_STATE EQ 'N'.
* Import from memory
  IMPORT
    IT_KSSK_UPDATE TO %_P0000000001
    IT_INOB_UPDATE TO %_P0000000002
    IT_AUSP_UPDATE TO %_P0000000003
  FROM MEMORY ID %_KEY.
  ELSE.
* Import from logfile
  IMPORT
    IT_KSSK_UPDATE TO %_P0000000001
    IT_INOB_UPDATE TO %_P0000000002
    IT_AUSP_UPDATE TO %_P0000000003
  FROM LOGFILE ID %_KEY.
  ENDIF.
* Call update task
  CALL FUNCTION 'NGC_CORE_CLF_DB_UPDATE'
     EXPORTING
       IT_KSSK_UPDATE = %_P0000000001
       IT_INOB_UPDATE = %_P0000000002
       IT_AUSP_UPDATE = %_P0000000003
  .
ENDFORM.