protected section.

  data MO_CUT type ref to CL_NGC_CORE_CHR_PERSISTENCY .
  class-data GO_SQL_ENVIRONMENT type ref to IF_OSQL_TEST_ENVIRONMENT .

  methods SET_CHARACTERISTICS
    importing
      !IT_CHARACTERISTIC type TH_NGC_CORE_CHR_PERS_DATA=>TT_I_CLFNCHARACTERISTIC
      !IV_KEYDATE type DATS .
  methods SET_CHARACTERISTIC_REFS
    importing
      !IT_CHARACTERISTIC_REF type TH_NGC_CORE_CHR_PERS_DATA=>TT_I_CLFNCHARCREFERENCE
      !IV_KEYDATE type DATS .
  methods SET_CHARACTERISTIC_VALUES
    importing
      !IT_CHARACTERISTIC_VALUE type TH_NGC_CORE_CHR_PERS_DATA=>TT_I_CLFNCHARCVALUE
      !IV_KEYDATE type DATS .
  methods SET_MARA
    importing
      !IT_MARA type TH_NGC_CORE_CHR_PERS_DATA=>TT_MARA .
  methods SET_MAKT
    importing
      !IT_MAKT type TH_NGC_CORE_CHR_PERS_DATA=>TT_MAKT .
  methods GET_EXPORTING_PARAMETERS
    exporting
      !ET_CHARACTERISTIC type NGCT_CORE_CHARC
      !ET_CHARACTERISTIC_VALUE type NGCT_CORE_CHARC_VALUE
      !ET_CHARACTERISTIC_REF type NGCT_CORE_CHARC_REF
      !ET_MESSAGE type NGCT_CORE_CHARC_MSG .
  methods GET_CHARC_DATA_INTERNAL
    importing
      !IT_CHARACTERISTIC_WITH_KEYDATE type TH_NGC_CORE_CHR_PERS_DATA=>TT_CHARACTERISTIC_WITH_KEYDATE
    exporting
      !ET_CHARACTERISTIC_IN type NGCT_CORE_CHARC_KEY
      !ET_CHARACTERISTIC_EXP type NGCT_CORE_CHARC .
  methods GET_CHARC_DATA_EXTERNAL
    importing
      !IT_CHARACTERISTIC_WITH_KEYDATE type TH_NGC_CORE_CHR_PERS_DATA=>TT_CHARACTERISTIC_WITH_KEYDATE
    exporting
      !ET_CHARACTERISTIC_IN type NGCT_CORE_CHARC_KEY_EXT
      !ET_CHARACTERISTIC_EXP type NGCT_CORE_CHARC .
  methods GET_CHARC_VALUE_DATA
    importing
      !IT_CHARC_VALUE type TH_NGC_CORE_CHR_PERS_DATA=>TT_CHARC_VALUE_WITH_KEYDATE
    exporting
      !ET_CHARC_VALUE_EXP type NGCT_CORE_CHARC_VALUE .
  methods GET_CHARC_REF_DATA
    importing
      !IT_CHARC_REF type TH_NGC_CORE_CHR_PERS_DATA=>TT_CHARC_REF_TABLE
    exporting
      !ET_CHARC_REF_EXP type NGCT_CORE_CHARC_REF .
  methods ASSERT_EXP_CHARACTERISTICS
    importing
      !IT_ACT type NGCT_CORE_CHARC
      !IT_EXP type NGCT_CORE_CHARC .
  methods ASSERT_EXP_CHARC_VALUES
    importing
      !IT_ACT type NGCT_CORE_CHARC_VALUE
      !IT_EXP type NGCT_CORE_CHARC_VALUE .
  methods ASSERT_EXP_CHARC_REFS
    importing
      !IT_ACT type NGCT_CORE_CHARC_REF
      !IT_EXP type NGCT_CORE_CHARC_REF .