*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ NGC_CORE_CONV_MULTOBJ

    IMPORTING
       REFERENCE(IV_CLASS_TYPE) TYPE !KLASSENART OPTIONAL
       REFERENCE(IV_CUSTOMIZING_HANDLING) TYPE !I DEFAULT 0
    EXPORTING
       REFERENCE(ET_MESSAGE) TYPE !SYMSG_TAB .