interface IF_NGC_CORE_CHR_PERSISTENCY
  public .


  methods READ_BY_EXTERNAL_KEY
    importing
      !IT_KEY type NGCT_CORE_CHARC_KEY_EXT
      !IV_LOCK type BOOLE_D default ABAP_FALSE
      !IV_SKIP_EXTERNAL type BOOLE_D default ABAP_FALSE
    exporting
      !ET_CHARACTERISTIC type NGCT_CORE_CHARC
      !ET_CHARACTERISTIC_VALUE type NGCT_CORE_CHARC_VALUE
      !ET_CHARACTERISTIC_REFERENCE type NGCT_CORE_CHARC_REF
      !ET_MESSAGE type NGCT_CORE_CHARC_MSG .
  methods READ_BY_INTERNAL_KEY
    importing
      !IT_KEY type NGCT_CORE_CHARC_KEY
      !IV_LOCK type BOOLE_D default ABAP_FALSE
      !IV_SKIP_EXTERNAL type BOOLE_D default ABAP_FALSE
    exporting
      !ET_CHARACTERISTIC type NGCT_CORE_CHARC
      !ET_CHARACTERISTIC_VALUE type NGCT_CORE_CHARC_VALUE
      !ET_CHARACTERISTIC_REFERENCE type NGCT_CORE_CHARC_REF
      !ET_MESSAGE type NGCT_CORE_CHARC_MSG .
endinterface.