private section.

  methods GET_CLASSIFICATION_DATA
    importing
      !IT_CLASSIFICATION type TH_NGC_CORE_CLF_PERS_DATA=>TT_CLFN_WITH_KDATE
      !IT_VALUATION type TH_NGC_CORE_CLF_PERS_DATA=>TT_VAL_WITH_KDATE
    exporting
      !ET_CLASSIFICATION_KEY type NGCT_CORE_CLASSIFICATION_KEY
      !ET_CLASSIFICATION_EXP type NGCT_CORE_CLASSIFICATION .
  methods GET_AUSP_CHANGE_DATA
    importing
      !IT_AUSP_CHANGE type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_AUSP_CHANGES
    exporting
      !ET_AUSP_EXP type RMCLAUSP_TAB .
  methods GET_KSSK_CHANGE_DATA
    importing
      !IT_KSSK_CHANGE type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_KSSK_CHANGES
      !IT_CLASS_DATA type NGCT_CORE_CLASS
    exporting
      !ET_KSSK_INSERT_EXP type RMCLKSSK_TAB
      !ET_KSSK_DELETE_EXP type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_RMCLDEL .
  methods GET_INOB_CHANGE_DATA
    importing
      !IT_INOB_CHANGE type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_INOB_CHANGES
    exporting
      !ET_INOB_INSERT_EXP type TT_INOB
      !ET_INOB_DELETE_EXP type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_RINOB .
  methods GET_CLASSTYPE_DATA
    importing
      !IT_CLASSTYPE type TH_NGC_CORE_CLF_PERS_DATA=>TT_I_CLFNCLASSTYPE
    exporting
      !ET_CLASSTYPE_EXP type NGCT_CORE_CLASS_TYPE .
  methods GET_CLMDPC_DATA
    importing
      !IT_KSSK type RMCLKSSK_TAB
      !IT_AUSP type RMCLAUSP_TAB
    exporting
      !ET_CLMDPC type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_CLMDCP .
  methods GET_CHANGES
    importing
      !IT_CHANGE_DATA type NGCT_CORE_CLASSIFICATION_UPD
      !IT_INOB_DATA type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_INOB_CHANGES optional
      !IT_KSSK_DATA type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_KSSK_CHANGES optional
      !IT_AUSP_DATA type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_AUSP_CHANGES optional
      !IT_CLASS type NGCT_CORE_CLASS
      !IT_CLASSTYPE type TH_NGC_CORE_CLF_PERS_DATA=>TT_I_CLFNCLASSTYPE
    exporting
      !ET_AUSP_CHANGE type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_AUSP_CHANGES
      !ET_KSSK_CHANGE type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_KSSK_CHANGES .
  methods SET_CLASSIFICATION
    importing
      !IT_CLASSIFICATION type TH_NGC_CORE_CLF_PERS_DATA=>TT_I_CLFNOBJECTCLASS
      !IV_KEYDATE type DATS .
  methods SET_VALUATION
    importing
      !IT_VALUATION type TH_NGC_CORE_CLF_PERS_DATA=>TT_I_CLFNOBJECTCHARCVAL
      !IV_KEYDATE type DATS .
  methods SET_CLASSTYPES
    importing
      !IT_CLASSTYPE type TH_NGC_CORE_CLF_PERS_DATA=>TT_I_CLFNCLASSTYPE .
  methods SET_CLASSTYPES_OBJTYPE_REDUN
    importing
      !IT_TCLAO type TT_TCLAO .
  methods SET_NEXT_CUOBJ
    importing
      !IV_CUOBJ type CUOBN .
  methods EXPECT_DB_UPDATE
    importing
      !IT_AUSP type RMCLAUSP_TAB
      !IT_KSSK_INSERT type RMCLKSSK_TAB
      !IT_KSSK_DELETE type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_RMCLDEL
      !IT_INOB_INSERT type TT_INOB
      !IT_INOB_DELETE type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_RINOB
      !IT_CLMDPC type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_CLMDCP
      !IV_TIMES type I default 1 .
  methods SETUP .
  class-methods CLASS_SETUP .
  class-methods CLASS_TEARDOWN .
  methods GET_READ_EXPORTING_PARAMETERS
    exporting
      !ET_CLASSIFICATION type NGCT_CORE_CLASSIFICATION
      !ET_MESSAGE type NGCT_CORE_CLASSIFICATION_MSG .
  methods ASSERT_EXP_KSSK_CHANGES
    importing
      value(IT_ACT) type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_KSSK_CHANGES
      value(IT_EXP) type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_KSSK_CHANGES .
  methods ASSERT_EXP_AUSP_CHANGES
    importing
      value(IT_ACT) type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_AUSP_CHANGES
      value(IT_EXP) type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_AUSP_CHANGES .
  methods ASSERT_EXP_CLASSTYPES
    importing
      value(IT_ACT) type NGCT_CORE_CLASS_TYPE
      value(IT_EXP) type NGCT_CORE_CLASS_TYPE .
  methods ASSERT_EXP_KSSK_CREATES
    importing
      value(IT_ACT) type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_KSSK_CHANGES
      value(IT_EXP) type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_KSSK_CHANGES .