interface IF_NGC_CORE_CLF_DB_UPDATE
  public .


  methods NGC_CORE_CLF_DB_UPDATE
    importing
      value(IT_KSSK_UPDATE) type NGCT_CORE_CLF_KSSK_UPD
      value(IT_INOB_UPDATE) type NGCT_CORE_CLF_INOB_UPD
      value(IT_AUSP_UPDATE) type NGCT_CORE_CLF_AUSP_UPD .
  methods CLF_DB_UPDATE
    importing
      !IT_KSSK_INSERT_FM type RMCLKSSK_TAB
      !IT_KSSK_DELETE_FM type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_RMCLDEL
      !IT_INOB_INSERT_FM type TT_INOB
      !IT_INOB_DELETE_FM type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_RINOB
      !IT_AUSP_FM type RMCLAUSP_TAB
      !IT_CLMDCP type CL_NGC_CORE_CLF_PERSISTENCY=>LTY_T_CLMDCP
      !IV_AFTER_OBJ_CREATE type BOOLE_D default ABAP_FALSE .
endinterface.