interface IF_NGC_RAP_CLS_BAPI_UTIL
  public .


  methods CREATE_CLASS_API
    importing
      !IV_CLASS type KLASSE_D
      !IV_CLASSTYPE type KLASSENART
      !IV_CHANGENUMBER type AENNR optional
      !IS_CLASSBASIC type BAPI1003_BASIC
      !IS_CLASSDOCUMENT type BAPI1003_DOCU optional
      !IS_CLASSADDITIONAL type BAPI1003_ADD optional
      !IS_CLASSSTANDARD type BAPI1003_STAND optional
      !IT_CLASSKEYWORD type TT_BAPI1003_CATCH
      !IT_CLASSTEXT type TT_BAPI1003_LONGTEXT optional
      !IT_CLASSCHARC type TT_BAPI1003_CHARACT optional
    returning
      value(RT_RETURN) type BAPIRETTAB .
  methods CHANGE_CLASS_API
    importing
      !IV_CLASS type KLASSE_D
      !IV_CLASSTYPE type KLASSENART
      !IV_CHANGENUMBER type AENNR optional
      !IS_CLASSBASIC type BAPI1003_BASIC
      !IS_CLASSBASIC_NEW type BAPI1003_BASIC
      !IS_CLASSDOCUMENT type BAPI1003_DOCU optional
      !IS_CLASSDOCUMENT_NEW type BAPI1003_DOCU_NEW optional
      !IS_CLASSADDITIONAL type BAPI1003_ADD optional
      !IS_CLASSADDITIONAL_NEW type BAPI1003_ADD_NEW optional
      !IS_CLASSSTANDARD type BAPI1003_STAND optional
      !IS_CLASSSTANDARDNEW type BAPI1003_STAND_NEW optional
      !IT_CLASSKEYWORD type TT_BAPI1003_CATCH
      !IT_CLASSKEYWORD_NEW type TT_BAPI1003_CATCH_NEW
      !IT_CLASSTEXT type TT_BAPI1003_LONGTEXT optional
      !IT_CLASSTEXT_NEW type TT_BAPI1003_LONGTEXT optional
      !IT_CLASSCHARC type TT_BAPI1003_CHARACT optional
      !IT_CLASSCHARC_NEW type TT_BAPI1003_CHARACT_NEW optional
    returning
      value(RT_RETURN) type BAPIRETTAB .
  methods DELETE_CLASS_API
    importing
      !IV_CLASS type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASS-CLASS
      !IV_CLASSTYPE type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASS-CLASSTYPE
    returning
      value(RT_RETURN) type BAPIRETTAB .
  methods CLEAR_BAPI_BUFFER .
  methods DELETE_CLASSTEXT_API
    importing
      !IV_CLASS type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASS-CLASS
      !IV_CLASSTYPE type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASS-CLASSTYPE
      !IT_CLASSTEXT type TT_BAPI1003_LONGTEXT
    returning
      value(RT_RETURN) type BAPIRETTAB .
  methods GET_CLASSINTID_FROM_BUFFER
    importing
      !IV_CLASS type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASS-CLASS
      !IV_CLASSTYPE type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASS-CLASSTYPE
    returning
      value(RS_CLASSINTERNALID) type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASS-CLASSINTERNALID .
  methods GET_CLASSKEYWORD_FROM_BUFFER
    importing
      !IS_CLASSKEYWORD type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASSKEYWORD
    returning
      value(RS_CLASSKEYWORD) type CL_NGC_BIL_CLS=>LTY_CLFN_CLASS_CDS-S_CLASSKEYWORD .
endinterface.