private section.

  methods CHECK_INCOMPLETE_BY_SYSTEM
    importing
      !IO_CLASSIFICATION type ref to IF_NGC_CLASSIFICATION
      !IS_CLASSIFICATION_DATA type NGCS_CLASSIFICATION_DATA
    returning
      value(RT_INCOMPLETE_CHARACT) type NGCT_CHARACTERISTIC .
  methods GET_STATUSES_FOR_CLASSTYPE
    importing
      !IV_CLASSTYPE type KLASSENART
    exporting
      !ES_RELEASED_STATUS type TS_CLF_STATUS
      !ES_LOCKED_STATUS type TS_CLF_STATUS
      !ES_INCOMPLETE_STATUS type TS_CLF_STATUS
      !ES_INCOMPLETE_SYSTEM_STATUS type TS_CLF_STATUS .
  methods CHECK_INCONSISTENT
    importing
      !IO_CLASSIFICATION type ref to IF_NGC_CLASSIFICATION
      !IS_CLASSIFICATION_DATA type NGCS_CLASSIFICATION_DATA
    returning
      value(RV_INCONSISTENT) type ABAP_BOOL .