private section.

  methods CREATE_SINGLE_VALUE
    importing
      !IV_CHARCDATATYPE type ATFOR .
  methods UPDATE_SINGLE_VALUE
    importing
      !IV_CHARCDATATYPE type ATFOR .
  methods GET_EXPORTING_PARAMETERS
    exporting
      !ET_MAPPED type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-RESPONSE-T_MAPPED
      !ET_REPORTED type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-RESPONSE-T_REPORTED
      !ET_FAILED type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-RESPONSE-T_FAILED
      !ET_OUTPUT type IF_NGC_BIL_CLF=>TS_OBJCHARCVAL-READ-T_RESULT .