interface ZIF_CR_I_H_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCR_I_H,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE9809625954760077A',
 CREATE_ZCR_I_H                 TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE98096256FECBC477A',
 DELETE_ZCR_I_H                 TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE98096256FECBCC77A',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE980962595475FE77A',
 LOCK_ZCR_I_H                   TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE98096256FECBB877A',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE9809625954760477A',
 SAVE_ZCR_I_H                   TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE98096256FECBD477A',
 UNLOCK_ZCR_I_H                 TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE98096256FECBBC77A',
 UPDATE_ZCR_I_H                 TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE98096256FECBC877A',
 VALIDATE_ZCR_I_H               TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE98096256FECBD077A',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EE9809625954760277A',
      END OF ZCR_I_H,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCR_I_H,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_ZCR_I_H,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZCR_I_H,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_ZCR_I_H,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZCR_I_H,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF ZCR_I_H,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCR_I_H,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000D3A02B3881EE980962595475FA77A',
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000D3A02B3881EE980962595475FC77A',
      END OF ZCR_I_H,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCR_I_H,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EE98096256FECBB677A',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EE98096256FECBB277A',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EE98096256FECBC277A',
      END OF ZCR_I_H,
      BEGIN OF ZCR_I_H_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EE98096256FECBDA77A',
      END OF ZCR_I_H_LOCK,
      BEGIN OF ZCR_I_H_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EE98096256FECBD877A',
      END OF ZCR_I_H_MESSAGE,
      BEGIN OF ZCR_I_H_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EE98096256FECBDC77A',
      END OF ZCR_I_H_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCR_I_H,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCR_I_H,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000D3A02B3881EE98096256FECBA877A' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCR_I_H' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCR_I_H,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954760677A',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954760A77A',
 DELETE_DRAFT_WHN_ACTIVE_DELETE TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954761877A',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954761677A',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDAAD91CBA6A58C89F8',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954761477A',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954760E77A',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954761277A',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EE9809625954761077A',
      END OF ZCR_I_H,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '000D3A02B3881EE98096256FECBE077A',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCR_I_H                        TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EE98096256FECBAC77A',
 ZCR_I_H_LOCK                   TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EE98096256FECBB477A',
 ZCR_I_H_MESSAGE                TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EE98096256FECBB077A',
 ZCR_I_H_PROPERTY               TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EE98096256FECBC077A',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCR_I_H,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  UUID                           TYPE STRING VALUE 'UUID',
  REQUEST_ID                     TYPE STRING VALUE 'REQUEST_ID',
  TITLE                          TYPE STRING VALUE 'TITLE',
  CUST_NAME1                     TYPE STRING VALUE 'CUST_NAME1',
  CUST_NAME2                     TYPE STRING VALUE 'CUST_NAME2',
  COUNTRY_KEY                    TYPE STRING VALUE 'COUNTRY_KEY',
  CITY                           TYPE STRING VALUE 'CITY',
  POSTAL_CODE                    TYPE STRING VALUE 'POSTAL_CODE',
  STREET                         TYPE STRING VALUE 'STREET',
  TEL_NUM                        TYPE STRING VALUE 'TEL_NUM',
  STERM_1                        TYPE STRING VALUE 'STERM_1',
  STERM_2                        TYPE STRING VALUE 'STERM_2',
  CREATED_BY                     TYPE STRING VALUE 'CREATED_BY',
  CREATED_ON                     TYPE STRING VALUE 'CREATED_ON',
  CREATED_AT                     TYPE STRING VALUE 'CREATED_AT',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTADMINISTRATIVEDATAUUID    TYPE STRING VALUE 'DRAFTADMINISTRATIVEDATAUUID',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  DRAFTENTITYOPERATIONCODE       TYPE STRING VALUE 'DRAFTENTITYOPERATIONCODE',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF ZCR_I_H,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCR_I_H,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000D3A02B3881EE98096256FECBAE77A',
      END OF ZCR_I_H,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF ZCR_I_H,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '000D3A02B3881EE98096256FECBDE77A',
      END OF ZCR_I_H,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZCR_I_H,
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '000D3A02B3881EE9809625954761A77A',
      END OF ZCR_I_H,
    END OF SC_VALIDATION .
endinterface.