PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZEKKOEKPO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZEKKOEKPO-EBELN .
    FIELD ZEKKOEKPO-EBELP .
    FIELD ZEKKOEKPO-BUKRS .
    FIELD ZEKKOEKPO-BSART .
    FIELD ZEKKOEKPO-MATNR .
    FIELD ZEKKOEKPO-WERKS .
    FIELD ZEKKOEKPO-MEINS .
    FIELD ZEKKOEKPO-MENGE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZEKKOEKPO-EBELN .
    FIELD ZEKKOEKPO-EBELP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.