*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZEKKOEKPOU01.
                    "TABLEFRAME_ZEKKOEKPO
INCLUDE LZEKKOEKPOU02.
                    "TABLEPROC_ZEKKOEKPO