interface IF_EX_NGC_CLF_CHK_CHNG_VALUES
  public .


  interfaces IF_BADI_INTERFACE .

  methods CHECK_CHANGE_VALUES
    importing
      !IV_CLASSTYPE type KLASSENART
      !IS_CLASSIFICATION_KEY type NGCS_CLASSIFICATION_KEY
      !IT_CLASSIFICATION_REF_DATA type NGCT_CLASSIFICATION_REF_DATA
      !IT_CHANGE_VALUE type NGCT_VALUATION_CHARCVALUE_CHG
    changing
      !CV_ALLOWED type BOOLE_D
      !CT_MESSAGE type NGCT_MSG_WITH_INDEX .
endinterface.