interface IF_NGC_BIL_CHR_TRANSACTIONAL
  public .


  methods ADJUST_NUMBERS
    exporting
      !ET_CHARC_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_MAPPED_LATE
      !ET_CHARC_DESC_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_MAPPED_LATE
      !ET_CHARC_RSTR_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCRSTRCNTP-T_MAPPED_LATE
      !ET_CHARC_REF_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCREFTP-T_MAPPED_LATE
      !ET_CHARC_VAL_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALTP-T_MAPPED_LATE
      !ET_CHARC_VAL_DESC_MAPPED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCVALDESCTP-T_MAPPED_LATE .
  methods CHECK_BEFORE_SAVE
    exporting
      !ET_CHARC_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_FAILED
      !ET_CHARC_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCTP-T_REPORTED
      !ET_CHARC_DESC_FAILED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_FAILED
      !ET_CHARC_DESC_REPORTED type IF_NGC_BIL_CHR_C=>LTY_CLFNCHARCDESCTP-T_REPORTED .
endinterface.