interface IF_NGC_DRF_C
  public .


  constants GC_IDOC_TYPE_CLFMAS type EDI_DOCTYP value 'CLFMAS' ##NO_TEXT.
  constants GC_IDOC_TYPE_CLSMAS type EDI_DOCTYP value 'CLSMAS' ##NO_TEXT.
  constants GC_IDOC_TYPE_CHRMAS type EDI_DOCTYP value 'CHRMAS' ##NO_TEXT.
  constants GC_RCVPRT_LOG_SYS type EDI_RCVPRT value 'LS' ##NO_TEXT.
  constants GC_CLFMAS_DRF_TABLE_TYPE type DRF_REL_OBJECT_TYPE value 'NGCT_DRF_CLFMAS_OBJECT_KEY' ##NO_TEXT.
  constants GC_CLSMAS_DRF_TABLE_TYPE type DRF_REL_OBJECT_TYPE value 'NGCT_DRF_CLSMAS_OBJECT_KEY' ##NO_TEXT.
  constants GC_CHRMAS_DRF_TABLE_TYPE type DRF_REL_OBJECT_TYPE value 'NGCT_DRF_CHRMAS_OBJECT_KEY' ##NO_TEXT.
  constants GC_CLASSIFICATION_TYPE_OBJECT type KLMAF value 'O' ##NO_TEXT.
  constants GC_CLASSIFICATION_TYPE_CLASS type KLMAF value 'K' ##NO_TEXT.
  constants GC_CLFMAS_DRF_OUTB_IMPL type DRF_OUTB_IMPL value 'CLF_CLFMAS' ##NO_TEXT.
  constants GC_CLSMAS_DRF_OUTB_IMPL type DRF_OUTB_IMPL value 'CLF_CLSMAS' ##NO_TEXT.
  constants GC_CHRMAS_DRF_OUTB_IMPL type DRF_OUTB_IMPL value 'CLF_CHRMAS' ##NO_TEXT.
  constants GC_CLF_EWM_DRF_OUTB_IMPL type DRF_OUTB_IMPL value 'EWM_0011' ##NO_TEXT.
  constants GC_CLS_EWM_DRF_OUTB_IMPL type DRF_OUTB_IMPL value 'EWM_0044' ##NO_TEXT.
  constants GC_CHR_EWM_DRF_OUTB_IMPL type DRF_OUTB_IMPL value 'EWM_0043' ##NO_TEXT.
  constants GC_CLF_DRF_BO_TYPE type MDG_OBJECT_TYPE_CODE_BS value 'DRF_0011' ##NO_TEXT.
  constants GC_CLS_DRF_BO_TYPE type MDG_OBJECT_TYPE_CODE_BS value 'DRF_0044' ##NO_TEXT.
  constants GC_CHR_DRF_BO_TYPE type MDG_OBJECT_TYPE_CODE_BS value 'DRF_0043' ##NO_TEXT.
  constants GC_OUTB_PARAM_PACK_SIZE_BULK type DRF_OUTB_PARAM_NAME value 'PACK_SIZE_BULK' ##NO_TEXT.
  constants GC_PACK_SIZE_BULK_MAX type DRF_OUTB_PARAM_VALUE value '2147483647' ##NO_TEXT.
  constants GC_QUEUE_NAME_CLS_CHR type STRING value 'EWMDRFCLSCHR' ##NO_TEXT.
  constants GC_PRODUCT_HEADER_DBTABLE type TABELLE value 'MARA' ##NO_TEXT.
  constants GC_BATCH_MAT_LEVEL_DBTABLE type TABELLE value 'MCH1' ##NO_TEXT.
  constants GC_BATCH_CLASSTYPE_MAT_LEVEL type KLASSENART value '023' ##NO_TEXT.
  constants GC_EWM_CLASSTYPE_VERSION type KLASSENART value '230' ##NO_TEXT.
endinterface.