*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LNGC_DMCU01.
                    "DMC_MIG_CHARACTERISTIC
INCLUDE LNGC_DMCU02.
                    "DMC_MIG_CLASS
INCLUDE LNGC_DMCU03.
                    "DMC_MIG_CLASSIFICATION
INCLUDE LNGC_DMCU04.
                    "DMC_MIG_CLASS_HIERA