CLASS tc_ngc_bil_clf_objectcharc DEFINITION
  PUBLIC
  INHERITING FROM tc_ngc_bil_clf
  ABSTRACT
  CREATE PUBLIC
  FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS

  GLOBAL FRIENDS cl_ngc_bil_clf .

  PUBLIC SECTION.