private section.

  methods SETUP .
  class-methods CLASS_SETUP .
  class-methods CLASS_TEARDOWN .
  methods SET_CLASSES
    importing
      !IT_CLASS type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNCLASS
      !IV_KEYDATE type DATS .
  methods SET_CLASS_CHARCS
    importing
      !IT_CLASS_CHARC type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNCLASSHIERCHARC
      !IV_KEYDATE type DATUV .
  methods SET_CLASS_STATUSES
    importing
      !IT_CLASS_STATUS type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNCLASSSTATUS .
  methods SET_CHARC_VALUE
    importing
      !IT_CHARC_VALUE type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNOBJECTCHARCVALUEBASIC .
  methods SET_CLASS_CLASSIFICATION_BASIC
    importing
      !IT_CLASS_CLASSIFICATION type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNOBJECTCLASSBASIC .
  methods SET_CHARACTERISTIC_DATA
    importing
      !IT_CHARC_KEY type NGCT_CORE_CHARC_KEY
      !IT_CHARACTERISTIC type NGCT_CORE_CHARC optional
      !IT_CHARC_VALUE type NGCT_CORE_CHARC_VALUE optional
      !IT_CHARC_REF type NGCT_CORE_CHARC_REF optional .
  methods GET_EXPORTING_PARAMETERS
    exporting
      !ET_CLASSES type NGCT_CORE_CLASS
      !ET_CLASS_CHARACTERISTICS type NGCT_CORE_CLASS_CHARACTERISTIC
      !ET_CLASS_CHARACTERISTIC_VALUES type NGCT_CORE_CLASS_CHARC_VALUE
      !ET_CHARACTERISTIC_REFERENCE type NGCT_CORE_CHARC_REF
      !ET_MESSAGE type NGCT_CORE_CLASS_MSG .
  methods GET_CLASS_DATA_EXTERNAL
    importing
      !IT_CLASS_WITH_KEYDATE type TH_NGC_CORE_CLS_PERS_DATA=>TT_CLASS_WITH_KEYDATE
    exporting
      !ET_CLASS_EXP type NGCT_CORE_CLASS
      !ET_CLASS_IN type NGCT_CORE_CLASS_KEY_EXT .
  methods GET_CLASS_DATA_INTERNAL
    importing
      !IT_CLASS_WITH_KEYDATE type TH_NGC_CORE_CLS_PERS_DATA=>TT_CLASS_WITH_KEYDATE
    exporting
      !ET_CLASS_EXP type NGCT_CORE_CLASS
      !ET_CLASS_IN type NGCT_CORE_CLASS_KEY .
  methods GET_CLASS_CHARC_DATA
    importing
      !IT_CLASS_CHARC_WITH_KDATE type TH_NGC_CORE_CLS_PERS_DATA=>TT_CLASS_CHR_WITH_KEYDATE
    exporting
      !ET_CLASS_CHARC_EXP type NGCT_CORE_CLASS_CHARACTERISTIC
      !ET_CHARACTERISTIC_KEY type NGCT_CORE_CHARC_KEY
      !ET_CHARACTERISTIC type NGCT_CORE_CHARC .
  methods GET_CHARC_VALUE_DATA
    importing
      !IT_CLASS_CHARC_WITH_KDATE type TH_NGC_CORE_CLS_PERS_DATA=>TT_CLASS_CHR_WITH_KEYDATE
      !IT_CHARC_VALUE type NGCT_CORE_CHARC_VALUE
      !IT_CHARC_VALUE_INH_OVERWRITE type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNOBJECTCHARCVALUEBASIC optional
    exporting
      !ET_CHARC_VALUE_EXP type NGCT_CORE_CLASS_CHARC_VALUE .
  methods GET_CHARC_REF_DATA
    importing
      !IT_CHARC_REF type NGCT_CORE_CHARC_REF
    exporting
      !ET_CHARC_REF_EXP type NGCT_CORE_CHARC_REF .
  methods GET_CLASS_STATUS_DATA
    importing
      !IT_CLASS_STATUS type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNCLASSSTATUS
    exporting
      !ET_CLASS_STATUS_EXP type NGCT_CORE_CLASS_STATUS .
  methods ASSERT_EXP_CLASSES
    importing
      !IT_ACT type NGCT_CORE_CLASS
      !IT_EXP type NGCT_CORE_CLASS .
  methods ASSERT_EXP_CLASS_CHARCS
    importing
      !IT_ACT type NGCT_CORE_CLASS_CHARACTERISTIC
      !IT_EXP type NGCT_CORE_CLASS_CHARACTERISTIC .
  methods ASSERT_EXP_CHARC_VALUES
    importing
      value(IT_ACT) type NGCT_CORE_CLASS_CHARC_VALUE
      value(IT_EXP) type NGCT_CORE_CLASS_CHARC_VALUE .
  methods ASSERT_EXP_CHARC_REF
    importing
      value(IT_ACT) type NGCT_CORE_CHARC_REF
      value(IT_EXP) type NGCT_CORE_CHARC_REF .
  methods ASSERT_EXP_STATUSES
    importing
      !IT_ACT type NGCT_CORE_CLASS_STATUS
      !IT_EXP type NGCT_CORE_CLASS_STATUS .
  methods SET_CHARCBASIC
    importing
      !IT_CHARCBASIC type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNCHARCBASIC .
  methods SET_CLASS_CHARCBASIC
    importing
      !IT_CLASS_CHARCBASIC type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNCLASSCHARCBASIC .
  methods SET_CLASS_SUPERIOR
    importing
      !IT_CLASS_SUPERIOR type TH_NGC_CORE_CLS_PERS_DATA=>TT_I_CLFNCLASSSUPERIOR
      !IV_KEYDATE type DATUV .