PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_OBJNAM.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD RB_PROG .
  FIELD RB_FUGR .
  FIELD RB_FUNC .
  FIELD RB_CLAS .
    MODULE %_RADIOBUTTON_GROUP_GRP1                          .
ENDCHAIN.


CHAIN.
  FIELD RB_PROG .
  FIELD RB_FUGR .
  FIELD RB_FUNC .
  FIELD RB_CLAS .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

CHAIN.
  FIELD  S_OBJNAM-LOW.
  FIELD  S_OBJNAM-HIGH.
  MODULE %_S_OBJNAM.
ENDCHAIN.

CHAIN.
  FIELD RB_PROG .
  FIELD RB_FUGR .
  FIELD RB_FUNC .
  FIELD RB_CLAS .
  FIELD  S_OBJNAM-LOW.
  FIELD  S_OBJNAM-HIGH.
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.