private section.

  methods SETUP .
  methods GET_CHARC_VALUE_FM_DATA
    importing
      !IT_CHARC_VALUE type TH_NGC_CORE_CHR_PERS_DATA=>TT_CHARC_VALUE_FM
    exporting
      !ET_CHARC_VALUE_EXP type NGCT_CORE_CHARC_VALUE
      !ET_CHARC_VALUE_IN type IF_NGC_CORE_CHR_UTIL_FUNCMOD=>TT_RCTVALUES .
  methods SET_FUNCTION_MODULE_EXISTING
    importing
      !IV_FUNCTION_NAME type RS38L_FNAM .
  methods SET_FUNCTION_MODULE_VALUES
    importing
      !IV_FUNCTION_NAME type RS38L_FNAM
      !IV_CHARACTERISTIC type ATNAM
      !IV_CHARCINTERNALID type ATINN
      !IT_VALUES type IF_NGC_CORE_CHR_UTIL_FUNCMOD=>TT_RCTVALUES .
  methods SET_CHARC_PHRASED
    importing
      !IV_CHARCINTERNALID type ATINN .
  methods SET_PHRASE_TEXT
    importing
      !IV_PHRASE_KEY type RCGATF4PHR-PHRKEY
      !IV_PHRASE_CODE type RCGATF4PHR-PHRCODE .