private section.

  data MS_CHARACTERISTIC_HEADER type NGCS_CHARACTERISTIC .
  data MT_DOMAIN_VALUE type NGCT_CHARACTERISTIC_VALUE .
  data MT_CHARACTERISTIC_REF type NGCT_CHARACTERISTIC_REF .
  data MV_DOMAIN_VALUES_POPULATED type ABAP_BOOL .
  data MO_CHR_PERSISTENCY type ref to IF_NGC_CORE_CHR_PERSISTENCY .