*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ NGC_IRF_GET_CLF_DATA

    IMPORTING
       REFERENCE(IV_OBJ_TAB) TYPE !TABELLE
       REFERENCE(IV_OBJEK) TYPE !AUSP-OBJEK
       REFERENCE(IV_FATHER_ID) TYPE !GSS_DEP_FATHER
       REFERENCE(IS_EXIT_DATA) TYPE !GSS_S_EXIT
    EXPORTING
       REFERENCE(ET_CLF_DATA) TYPE !GSS_T_TRANSFER .