*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LNGC_IRFU01.
                    "NGC_IRF_EQUI
INCLUDE LNGC_IRFU02.
                    "NGC_IRF_GET_CLF_DATA
INCLUDE LNGC_IRFU03.
                    "NGC_IRF_MCH1